/* * */

import { Ride, RideSchema } from '@/rides/ride.js';
import { z } from 'zod';

import { FileExportBaseSchema } from './common.js';

/* * */

export const FlatRideSchema = z.object({
	_id: z.string(),
	agency_id: z.string(),
	analysis_AT_LEAST_ONE_VEHICLE_EVENT_ON_FIRST_STOP_grade: z.string(),
	analysis_AT_LEAST_ONE_VEHICLE_EVENT_ON_FIRST_STOP_reason: z.string(),
	analysis_ENDED_AT_LAST_STOP_grade: z.string(),
	analysis_ENDED_AT_LAST_STOP_reason: z.string(),
	analysis_EXPECTED_APEX_VALIDATION_INTERVAL_grade: z.string(),
	analysis_EXPECTED_APEX_VALIDATION_INTERVAL_reason: z.string(),
	analysis_EXPECTED_DRIVER_ID_QTY_grade: z.string(),
	analysis_EXPECTED_DRIVER_ID_QTY_reason: z.string(),
	analysis_EXPECTED_START_TIME_grade: z.string(),
	analysis_EXPECTED_START_TIME_reason: z.string(),
	analysis_EXPECTED_START_TIME_value: z.number(),
	analysis_EXPECTED_VEHICLE_EVENT_DELAY_grade: z.string(),
	analysis_EXPECTED_VEHICLE_EVENT_DELAY_reason: z.string(),
	analysis_EXPECTED_VEHICLE_EVENT_INTERVAL_grade: z.string(),
	analysis_EXPECTED_VEHICLE_EVENT_INTERVAL_reason: z.string(),
	analysis_EXPECTED_VEHICLE_EVENT_QTY_expected_qty: z.number(),
	analysis_EXPECTED_VEHICLE_EVENT_QTY_found_qty: z.number(),
	analysis_EXPECTED_VEHICLE_EVENT_QTY_grade: z.string(),
	analysis_EXPECTED_VEHICLE_EVENT_QTY_reason: z.string(),
	analysis_EXPECTED_VEHICLE_ID_QTY_grade: z.string(),
	analysis_EXPECTED_VEHICLE_ID_QTY_reason: z.string(),
	analysis_MATCHING_APEX_LOCATIONS_grade: z.string(),
	analysis_MATCHING_APEX_LOCATIONS_reason: z.string(),
	analysis_MATCHING_VEHICLE_IDS_grade: z.string(),
	analysis_MATCHING_VEHICLE_IDS_reason: z.string(),
	analysis_SIMPLE_ONE_APEX_VALIDATION_grade: z.string(),
	analysis_SIMPLE_ONE_APEX_VALIDATION_reason: z.string(),
	analysis_SIMPLE_ONE_VEHICLE_EVENT_OR_APEX_VALIDATION_grade: z.string(),
	analysis_SIMPLE_ONE_VEHICLE_EVENT_OR_APEX_VALIDATION_reason: z.string(),
	analysis_SIMPLE_THREE_VEHICLE_EVENTS_grade: z.string(),
	analysis_SIMPLE_THREE_VEHICLE_EVENTS_reason: z.string(),
	analysis_SIMPLE_THREE_VEHICLE_EVENTS_stop_ids_first: z.string(),
	analysis_SIMPLE_THREE_VEHICLE_EVENTS_stop_ids_last: z.string(),
	analysis_SIMPLE_THREE_VEHICLE_EVENTS_stop_ids_middle: z.string(),
	analysis_TRANSACTION_SEQUENTIALITY_expected_qty: z.number(),
	analysis_TRANSACTION_SEQUENTIALITY_found_qty: z.number(),
	analysis_TRANSACTION_SEQUENTIALITY_grade: z.string(),
	analysis_TRANSACTION_SEQUENTIALITY_missing_qty: z.number(),
	analysis_TRANSACTION_SEQUENTIALITY_reason: z.string(),
	apex_locations_qty: z.number(),
	apex_on_board_refunds_amount: z.number(),
	apex_on_board_refunds_qty: z.number(),
	apex_on_board_sales_amount: z.number(),
	apex_on_board_sales_qty: z.number(),
	apex_validations_qty: z.number(),
	created_at: z.number(),
	driver_ids: z.string(),
	end_time_observed: z.number(),
	end_time_scheduled: z.number(),
	extension_observed: z.number(),
	extension_scheduled: z.number(),
	hashed_shape_id: z.string(),
	hashed_trip_id: z.string(),
	headsign: z.string(),
	is_locked: z.boolean(),
	line_id: z.number(),
	operational_date: z.string(),
	passengers_estimated: z.number(),
	passengers_observed: z.number(),
	passengers_observed_on_board_sales_amount: z.number(),
	passengers_observed_on_board_sales_qty: z.number(),
	passengers_observed_prepaid_amount: z.number(),
	passengers_observed_prepaid_qty: z.number(),
	passengers_observed_subscription_qty: z.number(),
	pattern_id: z.string(),
	plan_id: z.string(),
	route_id: z.string(),
	seen_first_at: z.number(),
	seen_last_at: z.number(),
	start_time_observed: z.number(),
	start_time_scheduled: z.number(),
	system_status: z.string(),
	trip_id: z.string(),
	updated_at: z.number(),
	vehicle_ids: z.string(),
});

export const RideExportSchema = FileExportBaseSchema.extend({
	data: FlatRideSchema,
	properties: z.object({
		agency_id: RideSchema.shape.agency_id.optional(),
		end_date: RideSchema.shape.end_time_scheduled,
		line_id: RideSchema.shape.line_id.optional(),
		start_date: RideSchema.shape.start_time_scheduled,
	}),
	scope: z.literal('ride'),
	type: z.literal('ride'),
}).strict();

export function parseRideToExport(ride: Ride): z.infer<typeof RideExportSchema>['data'] {
	return {
		_id: ride._id,
		agency_id: ride.agency_id,
		analysis_AT_LEAST_ONE_VEHICLE_EVENT_ON_FIRST_STOP_grade: ride.analysis?.AT_LEAST_ONE_VEHICLE_EVENT_ON_FIRST_STOP?.grade ?? '',
		analysis_AT_LEAST_ONE_VEHICLE_EVENT_ON_FIRST_STOP_reason: ride.analysis?.AT_LEAST_ONE_VEHICLE_EVENT_ON_FIRST_STOP?.reason ?? '',
		analysis_ENDED_AT_LAST_STOP_grade: ride.analysis?.ENDED_AT_LAST_STOP?.grade ?? '',
		analysis_ENDED_AT_LAST_STOP_reason: ride.analysis?.ENDED_AT_LAST_STOP?.reason ?? '',
		analysis_EXPECTED_APEX_VALIDATION_INTERVAL_grade: ride.analysis?.EXPECTED_APEX_VALIDATION_INTERVAL?.grade ?? '',
		analysis_EXPECTED_APEX_VALIDATION_INTERVAL_reason: ride.analysis?.EXPECTED_APEX_VALIDATION_INTERVAL?.reason ?? '',
		analysis_EXPECTED_DRIVER_ID_QTY_grade: ride.analysis?.EXPECTED_DRIVER_ID_QTY?.grade ?? '',
		analysis_EXPECTED_DRIVER_ID_QTY_reason: ride.analysis?.EXPECTED_DRIVER_ID_QTY?.reason ?? '',
		analysis_EXPECTED_START_TIME_grade: ride.analysis?.EXPECTED_START_TIME?.grade ?? '',
		analysis_EXPECTED_START_TIME_reason: ride.analysis?.EXPECTED_START_TIME?.reason ?? '',
		analysis_EXPECTED_START_TIME_value: ride.analysis?.EXPECTED_START_TIME?.value ?? 0,
		analysis_EXPECTED_VEHICLE_EVENT_DELAY_grade: ride.analysis?.EXPECTED_VEHICLE_EVENT_DELAY?.grade ?? '',
		analysis_EXPECTED_VEHICLE_EVENT_DELAY_reason: ride.analysis?.EXPECTED_VEHICLE_EVENT_DELAY?.reason ?? '',
		analysis_EXPECTED_VEHICLE_EVENT_INTERVAL_grade: ride.analysis?.EXPECTED_VEHICLE_EVENT_INTERVAL?.grade ?? '',
		analysis_EXPECTED_VEHICLE_EVENT_INTERVAL_reason: ride.analysis?.EXPECTED_VEHICLE_EVENT_INTERVAL?.reason ?? '',
		analysis_EXPECTED_VEHICLE_EVENT_QTY_expected_qty: ride.analysis?.EXPECTED_VEHICLE_EVENT_QTY?.expected_qty ?? 0,
		analysis_EXPECTED_VEHICLE_EVENT_QTY_found_qty: ride.analysis?.EXPECTED_VEHICLE_EVENT_QTY?.found_qty ?? 0,
		analysis_EXPECTED_VEHICLE_EVENT_QTY_grade: ride.analysis?.EXPECTED_VEHICLE_EVENT_QTY?.grade ?? '',
		analysis_EXPECTED_VEHICLE_EVENT_QTY_reason: ride.analysis?.EXPECTED_VEHICLE_EVENT_QTY?.reason ?? '',
		analysis_EXPECTED_VEHICLE_ID_QTY_grade: ride.analysis?.EXPECTED_VEHICLE_ID_QTY?.grade ?? '',
		analysis_EXPECTED_VEHICLE_ID_QTY_reason: ride.analysis?.EXPECTED_VEHICLE_ID_QTY?.reason ?? '',
		analysis_MATCHING_APEX_LOCATIONS_grade: ride.analysis?.MATCHING_APEX_LOCATIONS?.grade ?? '',
		analysis_MATCHING_APEX_LOCATIONS_reason: ride.analysis?.MATCHING_APEX_LOCATIONS?.reason ?? '',
		analysis_MATCHING_VEHICLE_IDS_grade: ride.analysis?.MATCHING_VEHICLE_IDS?.grade ?? '',
		analysis_MATCHING_VEHICLE_IDS_reason: ride.analysis?.MATCHING_VEHICLE_IDS?.reason ?? '',
		analysis_SIMPLE_ONE_APEX_VALIDATION_grade: ride.analysis?.SIMPLE_ONE_APEX_VALIDATION?.grade ?? '',
		analysis_SIMPLE_ONE_APEX_VALIDATION_reason: ride.analysis?.SIMPLE_ONE_APEX_VALIDATION?.reason ?? '',
		analysis_SIMPLE_ONE_VEHICLE_EVENT_OR_APEX_VALIDATION_grade: ride.analysis?.SIMPLE_ONE_VEHICLE_EVENT_OR_APEX_VALIDATION?.grade ?? '',
		analysis_SIMPLE_ONE_VEHICLE_EVENT_OR_APEX_VALIDATION_reason: ride.analysis?.SIMPLE_ONE_VEHICLE_EVENT_OR_APEX_VALIDATION?.reason ?? '',
		analysis_SIMPLE_THREE_VEHICLE_EVENTS_grade: ride.analysis?.SIMPLE_THREE_VEHICLE_EVENTS?.grade ?? '',
		analysis_SIMPLE_THREE_VEHICLE_EVENTS_reason: ride.analysis?.SIMPLE_THREE_VEHICLE_EVENTS?.reason ?? '',
		analysis_SIMPLE_THREE_VEHICLE_EVENTS_stop_ids_first: ride.analysis?.SIMPLE_THREE_VEHICLE_EVENTS?.stop_ids_first?.join('|') ?? '',
		analysis_SIMPLE_THREE_VEHICLE_EVENTS_stop_ids_last: ride.analysis?.SIMPLE_THREE_VEHICLE_EVENTS?.stop_ids_last?.join('|') ?? '',
		analysis_SIMPLE_THREE_VEHICLE_EVENTS_stop_ids_middle: ride.analysis?.SIMPLE_THREE_VEHICLE_EVENTS?.stop_ids_middle?.join('|') ?? '',
		analysis_TRANSACTION_SEQUENTIALITY_expected_qty: ride.analysis?.TRANSACTION_SEQUENTIALITY?.expected_qty ?? 0,
		analysis_TRANSACTION_SEQUENTIALITY_found_qty: ride.analysis?.TRANSACTION_SEQUENTIALITY?.found_qty ?? 0,
		analysis_TRANSACTION_SEQUENTIALITY_grade: ride.analysis?.TRANSACTION_SEQUENTIALITY?.grade ?? '',
		analysis_TRANSACTION_SEQUENTIALITY_missing_qty: ride.analysis?.TRANSACTION_SEQUENTIALITY?.missing_qty ?? 0,
		analysis_TRANSACTION_SEQUENTIALITY_reason: ride.analysis?.TRANSACTION_SEQUENTIALITY?.reason ?? '',
		apex_locations_qty: ride.apex_locations_qty ?? 0,
		apex_on_board_refunds_amount: ride.apex_on_board_refunds_amount ?? 0,
		apex_on_board_refunds_qty: ride.apex_on_board_refunds_qty ?? 0,
		apex_on_board_sales_amount: ride.apex_on_board_sales_amount ?? 0,
		apex_on_board_sales_qty: ride.apex_on_board_sales_qty ?? 0,
		apex_validations_qty: ride.apex_validations_qty ?? 0,
		created_at: ride.created_at,
		driver_ids: (ride.driver_ids ?? []).join('|'),
		end_time_observed: ride.end_time_observed ?? 0,
		end_time_scheduled: ride.end_time_scheduled,
		extension_observed: ride.extension_observed ?? 0,
		extension_scheduled: ride.extension_scheduled,
		hashed_shape_id: ride.hashed_shape_id,
		hashed_trip_id: ride.hashed_trip_id,
		headsign: ride.headsign,
		is_locked: false,
		line_id: ride.line_id,
		operational_date: ride.operational_date,
		passengers_estimated: ride.passengers_estimated ?? 0,
		passengers_observed: ride.passengers_observed ?? 0,
		passengers_observed_on_board_sales_amount: ride.passengers_observed_on_board_sales_amount ?? 0,
		passengers_observed_on_board_sales_qty: ride.passengers_observed_on_board_sales_qty ?? 0,
		passengers_observed_prepaid_amount: ride.passengers_observed_prepaid_amount ?? 0,
		passengers_observed_prepaid_qty: ride.passengers_observed_prepaid_qty ?? 0,
		passengers_observed_subscription_qty: ride.passengers_observed_subscription_qty ?? 0,
		pattern_id: ride.pattern_id,
		plan_id: ride.plan_id,
		route_id: ride.route_id,
		seen_first_at: ride.seen_first_at ?? 0,
		seen_last_at: ride.seen_last_at ?? 0,
		start_time_observed: ride.start_time_observed ?? 0,
		start_time_scheduled: ride.start_time_scheduled,
		system_status: ride.system_status,
		trip_id: ride.trip_id,
		updated_at: ride.updated_at,
		vehicle_ids: (ride.vehicle_ids ?? []).join('|'),
	};
}
