export interface DataTableColumn<T> {

	/**
	 * Column accessor.
	 * You can use dot-notation for nested objects property drilling.
	 * (i.e. `department.name` or `department.company.name`)
	 */
	accessor: keyof T | (string & {})

	/**
	 * Whether the column is hidden.
	 * @default false
	 */
	hidden?: boolean

	/**
	 * Custom cell data render function.
	 * Accepts the current record and its index in `records` as arguments and returns a React node
	 * (remember that a string is a valid React node too).
	 *
	 * Will override the default render function for this column.
	 */
	render?: (record: T) => React.ReactNode

	/**
	 * Whether the column is sortable.
	 * @default false
	 */
	sortable?: boolean

	/**
	 * The key to be used for sorting.
	 * If not provided, the column accessor will be used.
	 */
	sortKey?: string

	/**
	 * Optional column header title.
	 * If not present, one will be generated by "humanizing" the provided column accessor.
	 * (i.e. `firstName` -> `First name`; `user.firstName` -> `User first name`)
	 */
	title?: React.ReactNode | string

	/**
	 * The width of the column in pixels.
	 * @default 100%
	 */
	width?: number

}

export interface DataTableColumnProps<T = Record<string, unknown>> {
	/**
	 * The columns to be displayed in the table.
	 */
	columns: DataTableColumn<T>[]
}

export interface DataTableProps<T> {

	/**
	 * The classnames to be applied to the table.
	 */
	classnames?: Partial<
		Record<'body' | 'cell' | 'footer' | 'header' | 'root' | 'row' | 'table' | 'tableWrapper', string>
	>

	/**
	 * The column configuration for the table.
	 */
	columns: DataTableColumn<T>[]

	/**
	 * The maximum height of the table in pixels.
	 * @default 100%
	 */
	maxHeight?: number

	/**
	 * Callback function to handle row click events.
	 * @param record - The data record for the clicked row.
	 */
	onRowClick?: (record: T) => void

	/**
	 * Callback function to handle row context menu events.
	 * @param record - The data record for the row where the context menu was triggered.
	 */
	onRowContextMenu?: (record: T) => void

	/**
	 * Callback function to handle row double-click events.
	 * @param record - The data record for the double-clicked row.
	 */
	onRowDoubleClick?: (record: T) => void

	/**
	 * The data to be displayed in the table.
	 */
	records: T[]

	/**
	 * The id of the table.
	 */
	rowIdAccessor?: keyof T | (string & {})

	/**
	 * Whether the table should have a search input.
	 * @default false
	 */
	search?: DataTableSearchProps<T>

	/**
	 * The title of the table.
	 */
	title?: string

}

export interface DataTableSearchProps<T> {

	/**
	 * The list of accessors to be used for searching.
	 */
	accessors: (keyof T | (string & {}))[]

	/**
	 * Whether the search functionality is enabled.
	 */
	hidden?: boolean

	/**
	 * The icon to be displayed in the search input.
	 * @default <SearchIcon />
	 */
	icon?: React.ReactNode

	/**
	 * Callback function to handle search input changes.
	 * @param value - The new search input value.
	 */
	onChange?: (value: string) => void

	/**
	 * Placeholder text for the search input.
	 */
	placeholder?: string

	/**
	 * The current value of the search input.
	 */
	value?: string

}

export interface DataTableTitleProps<T> {

	/**
	 * The search configuration for the table.
	 */
	search?: DataTableSearchProps<T>

	/**
	 * The title of the table.
	 */
	title?: string

}
