name: sae-db-local

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #
  
  mongo1:
    image: mongo:latest
    container_name: mongo1
    restart: unless-stopped
    hostname: mongo1
    depends_on:
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
    volumes:
      - ./replica.key:/data/replica.key:ro
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./secrets:/secrets
      - mongo1-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: >
      mongod --replSet rs0 --auth --keyFile /data/replica.key --bind_ip_all

  mongo2:
    image: mongo:latest
    container_name: mongo2
    restart: unless-stopped
    hostname: mongo2
    volumes:
      - ./replica.key:/data/replica.key:ro
      - mongo2-data:/data/db
    command: >
      mongod --replSet rs0 --auth --keyFile /data/replica.key --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongo3:
    image: mongo:latest
    container_name: mongo3
    restart: unless-stopped
    hostname: mongo3
    volumes:
      - ./replica.key:/data/replica.key:ro
      - mongo3-data:/data/db
    command: >
      mongod --replSet rs0 --auth --keyFile /data/replica.key --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data: