name: 'Backupd | Build & Publish'

on:
  workflow_dispatch:
  push:
    paths:
      - 'configs/backupd/**'
    branches:
      - production

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  backupd:
    runs-on: ubuntu-latest
    steps:
        # # #
      - name: Checkout repository
        uses: actions/checkout@v4
        # # #
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        # # #
      - name: Build package
        working-directory: .
        run: npm run build:backupd
        # # #

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # # #
      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          context: .
          file: ./configs/backupd/Dockerfile
          tags: ghcr.io/tmlmobilidade/backupd:${{ github.ref_name }}