name: 'Main'

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  version-number:
    runs-on: ubuntu-latest
    steps:
      - id: generate-version-number
        run: |
          version="$(date +%Y%m%d).$(date +%H%M).$(date +%S)"
          echo "Generated version: $version"
          echo "version_number=$version" >> "$GITHUB_OUTPUT"
    outputs:
      version_number: ${{ steps.generate-version-number.outputs.version_number }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish-connectors:
    needs: version-number
    uses: ./.github/workflows/publish-connectors.yml
    with:
      version_number: ${{ needs.version-number.outputs.version_number }}

  publish-lib:
    needs: version-number
    uses: ./.github/workflows/publish-lib.yml
    with:
      version_number: ${{ needs.version-number.outputs.version_number }}

