# # #

name: 'Publish to NPM'
description: 'This workflow coordinates the publishng of packages to NPM with a common version number.'

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  version-number:
    name: 'Version Number'
    runs-on: ubuntu-latest
    steps:
      - id: generate-version-number
        run: |
          version="$(date +%Y%m%d).$(date +%H%M).$(date +%S)"
          echo "Generated version: $version"
          echo "version_number=$version" >> "$GITHUB_OUTPUT"
    outputs:
      version_number: ${{ steps.generate-version-number.outputs.version_number }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish-lib:
    name: 'Publish Lib'
    runs-on: ubuntu-latest
    needs: version-number
    steps:
        # # #
      - name: Checkout repository
        uses: actions/checkout@v4
        # # #
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        # # #
      - name: Build package
        working-directory: .
        run: npm run build:lib
        # # #
      - name: Bump package version
        working-directory: packages/connectors
        run: npm version --no-git-tag-version ${{ needs.version-number.outputs.version_number }}
        # # #
      - name: Publish package to NPM
        working-directory: packages/lib
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish-connectors:
    name: 'Publish Connectors'
    runs-on: ubuntu-latest
    needs: version-number
    steps:
        # # #
      - name: Checkout repository
        uses: actions/checkout@v4
        # # #
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        # # #
      - name: Build package
        working-directory: .
        run: npm run build:connectors
        # # #
      - name: Bump package version
        working-directory: packages/connectors
        run: npm version --no-git-tag-version ${{ needs.version-number.outputs.version_number }}
        # # #
      - name: Publish package to NPM
        working-directory: packages/connectors
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

#   publish-connectors2:
#     name: 'Publish Connectors'
#     needs: publish-connectors
#     uses: ./.github/workflows/publish-connectors.yml
#     with:
#       version_number: ${{ needs.version-number.outputs.version_number }}