# # #

name: 'Packages | Publish to NPM'

on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - 'packages/**'
      - '.github/workflows/packages-publish-all.yml'

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  version-number:
    name: 'Version Number'
    runs-on: ubuntu-latest
    steps:
      - id: generate-version-number
        run: |
          version="$(date +%Y%m%d).$(date +%H%M).$(date +%S)"
          echo "Generated version: $version"
          echo "version_number=$version" >> "$GITHUB_OUTPUT"
    outputs:
      version_number: ${{ steps.generate-version-number.outputs.version_number }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish-connectors:
    runs-on: ubuntu-latest
    needs: version-number
    steps:
        # # #
      - name: Checkout repository
        uses: actions/checkout@v4
        # # #
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        # # #
      - name: Build package
        working-directory: .
        run: npm run build:connectors
        # # #
      - name: Bump package version
        working-directory: packages/connectors
        run: npm version --no-git-tag-version ${{ needs.version-number.outputs.version_number }}
        # # #
      - name: Publish package to NPM
        working-directory: packages/connectors
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish-interfaces:
    runs-on: ubuntu-latest
    needs: version-number
    steps:
        # # #
      - name: Checkout repository
        uses: actions/checkout@v4
        # # #
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        # # #
      - name: Build package
        working-directory: .
        run: npm run build:interfaces
        # # #
      - name: Bump package version
        working-directory: packages/interfaces
        run: npm version --no-git-tag-version ${{ needs.version-number.outputs.version_number }}
        # # #
      - name: Publish package to NPM
        working-directory: packages/interfaces
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish-lib:
    runs-on: ubuntu-latest
    needs: version-number
    steps:
        # # #
      - name: Checkout repository
        uses: actions/checkout@v4
        # # #
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        # # #
      - name: Build package
        working-directory: .
        run: npm run build:lib
        # # #
      - name: Bump package version
        working-directory: packages/lib
        run: npm version --no-git-tag-version ${{ needs.version-number.outputs.version_number }}
        # # #
      - name: Publish package to NPM
        working-directory: packages/lib
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish-tsconfig:
    runs-on: ubuntu-latest
    needs: version-number
    steps:
        # # #
      - name: Checkout repository
        uses: actions/checkout@v4
        # # #
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        # # #
      - name: Bump package version
        working-directory: packages/tsconfig
        run: npm version --no-git-tag-version ${{ needs.version-number.outputs.version_number }}
        # # #
      - name: Publish package to NPM
        working-directory: packages/tsconfig
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish-types:
    runs-on: ubuntu-latest
    needs: version-number
    steps:
        # # #
      - name: Checkout repository
        uses: actions/checkout@v4
        # # #
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        # # #
      - name: Build package
        working-directory: .
        run: npm run build:types
        # # #
      - name: Bump package version
        working-directory: packages/types
        run: npm version --no-git-tag-version ${{ needs.version-number.outputs.version_number }}
        # # #
      - name: Publish package to NPM
        working-directory: packages/types
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish-ui:
    runs-on: ubuntu-latest
    needs: version-number
    steps:
        # # #
      - name: Checkout repository
        uses: actions/checkout@v4
        # # #
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        # # #
      - name: Build package
        working-directory: .
        run: npm run build:ui
        # # #
      - name: Bump package version
        working-directory: packages/ui
        run: npm version --no-git-tag-version ${{ needs.version-number.outputs.version_number }}
        # # #
      - name: Publish package to NPM
        working-directory: packages/ui
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish-utils:
    runs-on: ubuntu-latest
    needs: version-number
    steps:
        # # #
      - name: Checkout repository
        uses: actions/checkout@v4
        # # #
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        # # #
      - name: Build package
        working-directory: .
        run: npm run build:utils
        # # #
      - name: Bump package version
        working-directory: packages/utils
        run: npm version --no-git-tag-version ${{ needs.version-number.outputs.version_number }}
        # # #
      - name: Publish package to NPM
        working-directory: packages/utils
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish-emails:
    runs-on: ubuntu-latest
    needs: version-number
    steps:
        # # #
      - name: Checkout repository
        uses: actions/checkout@v4
        # # #
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        # # #
      - name: Build package
        working-directory: .
        run: npm run build:emails
        # # #
      - name: Bump package version
        working-directory: packages/emails
        run: npm version --no-git-tag-version ${{ needs.version-number.outputs.version_number }}
        # # #
      - name: Publish package to NPM
        working-directory: packages/emails
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}