# # #

name: 'Packages | Test'

on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - '.github/workflows/packages-test-all.yml'
  pull_request:
    branches:
      - production
    paths:
      - 'packages/**'
      - '.github/workflows/packages-test-all.yml'

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  build:
    name: 'Builds and lints all packages'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # # #
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        # # #
      - name: Build all packages
        run: npm run build:packages
        # # #
      - name: Lint all packages
        run: npm run lint:packages
        # # #