name: 'connectors | Publish to npm'

on:
  workflow_call:
    inputs:
      version_number:
        required: true
        type: 'string'

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish:
    name: 'Publish package'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        with:
          node-version: 20

      - name: Build package
        working-directory: .
        run: npm run build:connectors

      - name: Bump package version
        run: npm version --no-git-tag-version ${{ inputs.version_number }}

      - name: Publish package to NPM
        working-directory: packages/connectors
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}