name: 'Publish TSConfig'

on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - packages/tsconfig/**

jobs:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish:
    name: 'Publish to NPM'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup Node
      #   uses: ./.github/actions/setup-node
      #   with:
      #     node-version: 20

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Bump package version
        working-directory: packages/tsconfig
        run: npx @helperkits/bumper bump

      - name: Publish package to NPM
        working-directory: packages/tsconfig
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}