name: 'tsconfig | Publish to npm'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - production
    paths:
      - 'packages/tsconfig/**/*'
      - '.github/workflows/publish-tsconfig.yml'
  push:
    branches:
      - production
    paths:
      - 'packages/tsconfig/**/*'
      - '.github/workflows/publish-tsconfig.yml'

jobs:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish:
    name: 'Publish package'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        with:
          node-version: 20

      - name: Bump package version
        working-directory: packages/tsconfig
        run: npx @helperkits/bumper bump

      - name: Publish package to NPM
        working-directory: packages/tsconfig
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}