name: 'create-tml-app | Publish to npm'

on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - 'cli/create-tml-app/**/*'
      - '.github/workflows/publish-create-tml-app.yml'

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish:
    name: 'Publish package'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        with:
          node-version: 20

      - name: Build package
        working-directory: .
        run: npm run build:create-tml-app

      - name: Bump package version
        working-directory: cli/create-tml-app
        run: npx @helperkits/bumper bump

      - name: Publish package to NPM
        working-directory: packages/connectors
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}