name: 'Test UI'

on:
  pull_request:
    branches:
      - production
    paths:
      - 'packages/ui/src/**/*'


  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
    
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}

    - name: Linting
      run: pnpm lint --filter=@tmlmobilidade/ui
